### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jmalm** [junalmeida/homeassistant-torque#28]
How do I install this integration?

I'm running Home Assistant 2024.3.1 in a docker container, with HACS 1.34.0.

I've done the following:

1. In HACS, added https://github.com/junalmeida/homeassistant-torque as a custom repository
2. In HACS > Custom repositories, clicked on Torque Logger
3. On the Torque Logger page, clicked Download

I get the following logs in home assistant:

```
homeassistant  | 2024-07-27 15:14:34.678 INFO (MainThread) [custom_components.hacs] <Integration junalmeida/homeassistant-torque> Running pre installation steps
homeassistant  | 2024-07-27 15:14:34.679 INFO (MainThread) [custom_components.hacs] <Integration junalmeida/homeassistant-torque> Pre installation steps completed
homeassistant  | 2024-07-27 15:14:34.679 INFO (MainThread) [custom_components.hacs] <Integration junalmeida/homeassistant-torque> Running installation steps
homeassistant  | 2024-07-27 15:14:36.465 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/junalmeida/homeassistant-torque/releases/download/main/torque_logger.zip
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/config/custom_components/hacs/base.py", line 730, in async_download_file
homeassistant  |     raise HacsException(
homeassistant  | custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/junalmeida/homeassistant-torque/releases/download/main/torque_logger.zip
homeassistant  | 2024-07-27 15:14:36.467 ERROR (MainThread) [custom_components.hacs] <Integration junalmeida/homeassistant-torque> Failed to download https://github.com/junalmeida/homeassistant-torque/releases/download/main/torque_logger.zip
homeassistant  | 2024-07-27 15:14:36.467 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [134938234596928] Error handling message: Unknown error (unknown_error) admin from 193.150.201.23 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
homeassistant  |     await func(hass, connection, msg)
homeassistant  |   File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
homeassistant  |     await repository.async_install()
homeassistant  |   File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
homeassistant  |     await self.async_install_repository(version=version)
homeassistant  |   File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
homeassistant  |     raise HacsException("Could not download, see log for details")
homeassistant  | custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

Is HACS not able to add a repo that doesn't have any releases? How do I install it manually?

The instructions say "Click install", but I can't find anywhere to click install.

**Comment by jmalm** [comment]
I managed to install it using instructions at https://community.home-assistant.io/t/how-to-make-default-torque-integration-work-in-home-assistant/528970/49.

But in the home assistant logs I get the following error:

```
homeassistant  | 2024-07-29 06:01:02.773 ERROR (MainThread) [custom_components.torque_logger] Missing profile name from torque data.
```

In Torque Pro, my profile is called "Kia e-Niro". Is there some config in Torque Pro that I'm missing? I don't see any configuration that can be done in Torque logger.

**Comment by JOHLC** [comment]
> I managed to install it using instructions at https://community.home-assistant.io/t/how-to-make-default-torque-integration-work-in-home-assistant/528970/49.
> 
> But in the home assistant logs I get the following error:
> 
> ```
> homeassistant  | 2024-07-29 06:01:02.773 ERROR (MainThread) [custom_components.torque_logger] Missing profile name from torque data.
> ```
> 
> In Torque Pro, my profile is called "Kia e-Niro". Is there some config in Torque Pro that I'm missing? I don't see any configuration that can be done in Torque logger.

Force close and reopen Torque on your phone when you see this, and it usually fixes that message for me

**Comment by nikito7** [comment]
Code needs updates

**Comment by TurnrDev** [comment]
Have you considered making this HACs compatible?

**Comment by JOHLC** [comment]
> Have you considered making this HACs compatible?

This is HACS compatible. You just have to add it as a custom repo:
![image](https://github.com/user-attachments/assets/f42329c9-3d09-42d9-bd0f-f1d9c5a918cc)
![image](https://github.com/user-attachments/assets/120c1ac4-e66c-4e47-8914-280c5d1b609f)

**Comment by nikito7** [comment]
> > Have you considered making this HACs compatible?
> 
> This is HACS compatible. You just have to add it as a custom repo: ![image](https://private-user-images.githubusercontent.com/63735432/357817342-f42329c9-3d09-42d9-bd0f-f1d9c5a918cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDA0MDMsIm5iZiI6MTcyMzY0MDEwMywicGF0aCI6Ii82MzczNTQzMi8zNTc4MTczNDItZjQyMzI5YzktM2QwOS00MmQ5LWJkMGYtZjFkOWM1YTkxOGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEyNTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZTUzNDk4NTFiZGRjYzYxYjVhOTMzYmRlZDIyNTcxYTBkYjc5NWE3MGNkNWJkZGZhMGQzMmM3YmFhMzYzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y2vkzFLLSutL4SMZUeamjlZkQpuSBvF2L6zCE2h7IYE) ![image](https://private-user-images.githubusercontent.com/63735432/357817398-120c1ac4-e66c-4e47-8914-280c5d1b609f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDA0MDMsIm5iZiI6MTcyMzY0MDEwMywicGF0aCI6Ii82MzczNTQzMi8zNTc4MTczOTgtMTIwYzFhYzQtZTY2Yy00ZTQ3LTg5MTQtMjgwYzVkMWI2MDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEyNTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NGQ4Mzk4ZTFkN2M5ZjNiZDA3N2IxNTlhMTMzNjU4OTE5MzQxMTliZTU1N2Q5NzdlN2I1NmYwODU4YTY4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CF2WgkPWcCmxUBQLuCwleK55kOQQJYP7gNQGsvnSaIw)

Install fails. Code needs update

**Comment by TurnrDev** [comment]
Installation via HACs fails it it's trying to download the latest release but you have none

**Comment by TurnrDev** [comment]
Not stale you silly bot

**Comment by TurnrDev** [comment]
It's not stale, it still needs fixing.
